# settings.py — константы и настройки

# Окно
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 850
FPS = 30

# Карта
MAP_WIDTH = 300
MAP_HEIGHT = 200
BASE_TILE_SIZE = 8

# Цвета тайлов
COLOR_GRASS = (106, 154, 64)
COLOR_FOREST = (58, 106, 26)
COLOR_WATER = (80, 136, 200)
COLOR_MOUNTAIN = (138, 138, 128)
COLOR_SAND = (208, 192, 144)
COLOR_BORDER = (106, 48, 48)
COLOR_SNOW = (240, 240, 240)
COLOR_SEA = (40, 80, 160)
COLOR_SHALLOW = (60, 140, 200)
COLOR_COAL = (60, 50, 40)
COLOR_IRON = (160, 100, 60)
COLOR_CLAY = (180, 160, 100)
COLOR_FERTILE = (90, 140, 50)

# Типы тайлов
TILE_GRASS = 0
TILE_FOREST = 1
TILE_WATER = 2
TILE_MOUNTAIN = 3
TILE_SAND = 4
TILE_BORDER = 5
TILE_SNOW = 6
TILE_SEA = 7
TILE_SHALLOW = 8
TILE_COAL = 9
TILE_IRON = 10
TILE_CLAY = 11
TILE_FERTILE = 12

TILE_COLORS = {
    TILE_GRASS: COLOR_GRASS,
    TILE_FOREST: COLOR_FOREST,
    TILE_WATER: COLOR_WATER,
    TILE_MOUNTAIN: COLOR_MOUNTAIN,
    TILE_SAND: COLOR_SAND,
    TILE_BORDER: COLOR_BORDER,
    TILE_SNOW: COLOR_SNOW,
    TILE_SEA: COLOR_SEA,
    TILE_SHALLOW: COLOR_SHALLOW,
    TILE_COAL: COLOR_COAL,
    TILE_IRON: COLOR_IRON,
    TILE_CLAY: COLOR_CLAY,
    TILE_FERTILE: COLOR_FERTILE,
}

TILE_NAMES = {
    TILE_GRASS: "Равнина",
    TILE_FOREST: "Лес",
    TILE_WATER: "Вода",
    TILE_MOUNTAIN: "Горы",
    TILE_SAND: "Песок",
    TILE_BORDER: "Граница",
    TILE_SNOW: "Снег",
    TILE_SEA: "Море",
    TILE_SHALLOW: "Мелководье",
    TILE_COAL: "Уголь",
    TILE_IRON: "Руда",
    TILE_CLAY: "Глина",
    TILE_FERTILE: "Плодородная",
}

# Режимы отображения
VIEW_NORMAL = 0
VIEW_BUILD = 1
VIEW_RESOURCES = 2

# Зум
ZOOM_MIN = 0.25
ZOOM_MAX = 4.0
ZOOM_STEP = 0.1

# Игровое время
TICKS_PER_DAY = 500